[package]
name = "rust-pipes"
version = "0.1.0"
edition = "2021"

[dependencies]
three-d = "0.16.3"
three-d-asset = "0.6.0"
rand = "0.8.5"
clap = { version = "4.4.6", features = ["derive", "cargo"] }
