[package]
name = "rust-pipes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = { version = "0.35.0", optional = true }
nalgebra = { version = "0.30.1", optional = true }
# glutin = { version = "*", optional = true }
three-d = { version = "*", optional = true }
rand = "0.8.5"

[features]
default = ["three_d_eng"]
k3d_engine = ["dep:kiss3d", "dep:nalgebra"]
three_d_eng = ["dep:three-d"]
